name: $project_name
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 path: ^1.8.0
 mineral: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
